### ISSUE TITLE
VintiCode producing NaNs with at least one output

### ISSUE THREAD

**Issue by G5STER** [ODU-CGA-CubeSat/orbit-propogator#5]
Failure in running VintiCode with input state vector X1, producing NaNs. But, the code runs fine with X2:

X1=
3009.3259436957
-4020.6187860063
4125.6669808177
3.256104600562435
6.145930407293207
3.604116020018543

X2=
_3009.325943695**6**_
-4020.6187860063
4125.6669808177
3.256104600562435
6.145930407293207
3.604116020018543

Note: only the last billionth decimal place in line 1 was changed by a single digit (from 7 to 6).

Potential reasons:
- Exceeding data range of variable type double

**Comment by G5STER** [comment]
Another instance:

X3=
1201.752113398
6418.04515572
578.123656594
-4.672720128
1.4304103
-6.081701284

**Comment by G5STER** [comment]
Issue found to originate in source propagator, Vinti6.c

**Comment by capsulecorplab** [comment]
Could be useful for debugging https://ro-che.info/articles/2020-01-11-gdb-break-on-nan

**Comment by G5STER** [comment]
Investigate if this error occurs within a certain range of altitudes and/or velocities.

**Comment by whizquiznext** [comment]
> 

For the state vector X1, I isolated a nan exception caused due to the square root of a negative number. On line 
627 of vinti6.c, looking at the equation:

shat = ( fabs(sqrf)/sqrf )*sqrt(gamma*rho02 + 2*rho0 - p)/ecc;

(gamma*rho02 + 2*rho0 - p) equates to -0.0, for input state vector x1. Hence, the square root of the same is returned as nan, causing variable shat to be nan and all other operations using 'shat' to also be nan.

This issue can be fixed by simply wrapping the operations inside sqrt within fabs.
So the modified equation on line 627 of vinti6.c would then be:
shat = (fabs(sqrf)/sqrf )*sqrt(fabs(gamma*rho02 + 2*rho0 - p))/ecc;

**Comment by whizquiznext** [comment]
> Another instance of failure:
> 
> State Vector = 1201.752113398 6418.04515572 578.123656594 -4.672720128 1.4304103 -6.081701284
> 
> but not:
> 
> State Vector = 1201.752113397 6418.04515572 578.123656594 -4.672720128 1.4304103 -6.081701284
> 
> And fails with:
> 
> State Vector = -3760.66175281 -3353.33213998 -4195.11923637 1.9917918 -6.65382392 3.53582729


For this issue. Looking at line 378 in vinti.c, 
ecc  = sqrt(ecc2); 
The value of ecc2 is -0.0 again for input vector:
1201.752113398
6418.04515572
578.123656594
-4.672720128
1.4304103
-6.081701284
Therefore, the square root of the negative number gives us a nan exception.
This can again be fixed by wrapping the operations inside sqrt with fabs. The code on line 378 would then be:
ecc  = sqrt(fabs(ecc2)); 

I think all the operations inside sqrt could be wrapped in fabs. I don't think this would cause any issues, and we should be free of nan issues hopefully. Does that make sense?

**Comment by shoaib-odu** [comment]
> Failure in running VintiCode with input state vector X1, producing NaNs. But, the code runs fine with X2:
> 
> X1= 3009.3259436957 -4020.6187860063 4125.6669808177 3.256104600562435 6.145930407293207 3.604116020018543
> 
> X2= _3009.325943695**6**_ -4020.6187860063 4125.6669808177 3.256104600562435 6.145930407293207 3.604116020018543
> 
> Note: only the last billionth decimal place in line 1 was changed by a single digit (from 7 to 6).
> 
> Potential reasons:
> 
> * Exceeding data range of variable type double

For the state vector X1, I isolated a nan exception caused due to the square root of a negative number. On line 627 of vinti6.c, looking at the equation:

shat = ( fabs(sqrf)/sqrf )sqrt(gammarho02 + 2*rho0 - p)/ecc;

(gammarho02 + 2rho0 - p) equates to -0.0, for input state vector x1. Hence, the square root of the same is returned as nan, causing variable shat to be nan and all other operations using 'shat' to also be nan.

This issue can be fixed by simply wrapping the operations inside sqrt within fabs.  So the modified equation on line 627 of vinti6.c would then be: 
shat = (fabs(sqrf)/sqrf )sqrt(fabs(gammarho02 + 2*rho0 - p))/ecc;

**Comment by shoaib-odu** [comment]
> Another instance of failure:
> 
> State Vector = 1201.752113398 6418.04515572 578.123656594 -4.672720128 1.4304103 -6.081701284
> 
> but not:
> 
> State Vector = 1201.752113397 6418.04515572 578.123656594 -4.672720128 1.4304103 -6.081701284
> 
> And fails with:
> 
> State Vector = -3760.66175281 -3353.33213998 -4195.11923637 1.9917918 -6.65382392 3.53582729

For this issue. Looking at line 378 in vinti.c,:
ecc = sqrt(ecc2); The value of ecc2 is -0.0 again for input vector: 
1201.752113398
6418.04515572
578.123656594
-4.672720128
1.4304103
-6.081701284

 Therefore, the square root of the negative number gives us a nan exception. This can again be fixed by wrapping the operations inside sqrt with fabs. The code on line 378 would then be: 
ecc = sqrt(fabs(ecc2));

I think all the operations inside sqrt could be wrapped in fabs. I don't think this would cause any issues, and we should be free of nan issues hopefully. Does that make sense?

**Comment by jabedrabboODU** [comment]
@shoaib-odu @G5STER Actually I traced along the code, and it seems that the culprit is the handling of the floating point precision within the Vinti6 function. 

As @shoaib-odu said, there is a Nan at line 627 when calculating the square root. The difference between using the first element of the space vector to be 3009.3259436956 or 3009.3259436957 is that one will have **(gamma*rho02 + 2*rho0 - p)** @ line 627 equal to **0**; the other would have it equal to **-2.2204460492503131e-16**.

I'm not sure about the exact precision required. However, we can fix the problem by either what @shoaib-odu suggested (but not actually sure if this is correct, as my assumption is that we might have negative values) or simply considering anything below a certain value to be considered equal to 0.

**Comment by G5STER** [comment]
Thanks @shoaib-odu, in commit [d0ffe75](https://github.com/ODU-CGA-CubeSat/orbit-propogator/commit/d0ffe75aaeca9fdeeb88c8aae6a1f9965fc244a2), I implemented your fix and it seems to be working now.

@jabedrabboODU I don't think this will introduce too much error; any negative number would have resulted in an invalid state vector anyway. The variables in question should in theory not be negative and I think the only instance where they are, are these -0.0_ values.
I agree though that there may some precision lost though due to taking absolute value and not redefining to zero. But, I'm not sure how to go about testing for that error.
